//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork25.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interactions
    {
        public int InteractionID { get; set; }
        public int ClientID { get; set; }
        public System.DateTime InteractionDate { get; set; }
        public int TypeID { get; set; }
        public string Notes { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual InteractionType InteractionType { get; set; }
    }
}
