//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseWork25.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseWork25Entities : DbContext
    {
        private static CourseWork25Entities _context;
        public static CourseWork25Entities GetContext()
        {
            if (_context == null)
                _context = new CourseWork25Entities();
            return _context;
        }
        public CourseWork25Entities()
            : base("name=CourseWork25Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientCategories> ClientCategories { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Interactions> Interactions { get; set; }
        public virtual DbSet<InteractionType> InteractionType { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
